language: python
python:
  - 3.8
  - 3.9
env:
  - DJANGO="==3.1"
  - DJANGO="==4.0"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==5.3.1
  - pip install coveralls==2.2.0
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: pypy
      env: DJANGO="==3.0"
